# **[Python datascience handbook](https://jakevdp.github.io/PythonDataScienceHandbook/01.01-help-and-documentation.html)**

## **Accesing the documentation**

In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [2]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


In [3]:
def square(a):
    """ return the square of a 

    Args:
        a (int): integer
    """
    return a**2

In [4]:
square?

Signature: square(a)
Docstring:
return the square of a 

Args:
    a (int): integer
File:      c:\users\david\onedrive - universidad de los andes\documentos\juan david\inteligencia artificial\python\python data science handbook\<ipython-input-3-9ca20b71e7cf>
Type:      function


In [5]:
square??

Signature: square(a)
Source:   
def square(a):
    """ return the square of a 

    Args:
        a (int): integer
    """
    return a**2
File:      c:\users\david\onedrive - universidad de los andes\documentos\juan david\inteligencia artificial\python\python data science handbook\<ipython-input-3-9ca20b71e7cf>
Type:      function


In [6]:
L = [1, 2, 3]

* For private attributes or methods

In [ ]:
L._

* wildcards

In [8]:
*Warning?

BytesWarning
DeprecationWarning
FutureWarning
ImportWarning
PendingDeprecationWarning
ResourceWarning
RuntimeWarning
SyntaxWarning
UnicodeWarning
UserWarning
Warning

In [7]:
str.*find*?

str.find
str.rfind

* Magic functions 

In [10]:
%timeit  L = [n**2 for n in range(1000)]

595 µs ± 40.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
%%timeit
L = []
for n in range(1000):
   L.append(n ** 2)

732 µs ± 57.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [12]:
!echo "printing from the shell"

"printing from the shell"


In [15]:
%pwd

'c:\\Users\\david\\OneDrive - Universidad de los Andes\\Documentos\\Juan David\\Inteligencia Artificial\\Python\\Python Data Science Handbook'

In [16]:
%ls

 El volumen de la unidad C es Windows
 El n�mero de serie del volumen es: 960D-BDC4

 Directorio de c:\Users\david\OneDrive - Universidad de los Andes\Documentos\Juan David\Inteligencia Artificial\Python\Python Data Science Handbook

04/04/2022  11:13 a.�m.    <DIR>          .
04/04/2022  11:13 a.�m.    <DIR>          ..
04/04/2022  12:13 p.�m.             7.333 Book.ipynb
               1 archivos          7.333 bytes
               2 dirs  17.987.166.208 bytes libres


* Use verbose %xmode Verbose to get a more explicit explanation of an error 

## **Introduction to numpy**

In [1]:
import numpy as np

In [2]:
a = np.array([1,4,2,5,3])
print(a)

[1 4 2 5 3]


In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
np.arange(0, 20, 2) # de 0 hasta 20 de a pasos de a 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0, 1, 5) # un array con 5 valores distanciados equitativamente que empiezan en 0 y terminan en 1 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.normal(0, 1, (3, 4))# una matriz de 3 x 4 con valores normalmente distribuidos con media 0 y desviación estándar 1 

array([[-0.79568698, -0.09152852, -1.06696158,  1.50574542],
       [ 0.87565562, -0.6819811 ,  0.103099  ,  0.50785354],
       [ 0.2952466 ,  0.07928415,  0.27025288, -1.12669175]])

In [10]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

* Atributos 

In [11]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [12]:
x1

array([5, 0, 3, 3, 7, 9])

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [15]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)# 3 capas de 4 filas por 5 columnas 
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [16]:
x2[0,0]

3

In [18]:
x2[1][2]

8

In [19]:
x2[1,2]

8

In [20]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [22]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

#### A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [25]:
x[2:8:2]

array([2, 4, 6])

In [23]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [26]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

#### Si cambiamos un subarray al final se cambia todo 

In [27]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [28]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [29]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [30]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
x = np.array([1, 2, 3])

In [36]:
x

array([1, 2, 3])

In [32]:
x.shape

(3,)

In [33]:
x.ndim

1

In [35]:
y = x.reshape((3, 1))
y.shape


(3, 1)

In [37]:
y

array([[1],
       [2],
       [3]])

In [38]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [39]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

#### First axis hace referencia a lo largo de las filas, es decir axis = 0
#### Second axis hace referencia a lo largo de las columnas, es decir axis = 1 

In [40]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [43]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [46]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [1, 4])
print(x1, x2, x3)

[1] [ 2  3 99] [99  3  2  1]


####  vectorización : aplicar la operación a todo el array y con esto internamente numpy aplica la operación a todos los valores del array

In [47]:
values = np.random.randint(1, 10, size=5)

#### Esto se conoce como u functions

In [48]:
print(1.0 / values)

[0.2        0.25       0.2        0.2        0.11111111]


#### Broadcasting : hacer uso de la vectorización con arrays de diferentes dimensiones

In [49]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

In [50]:
a + 5

array([5, 6, 7])

We can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

In [51]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])